### ISSUE TITLE
 not a valid add-on repository

### ISSUE THREAD

**Issue by YichGa** [Kajkac/ZTE-MC-Home-assistant#21]
Hi,

can anyone help please? Can't add the repo in the HA. I get the following message:

https://github.com/Kajkac/ZTE-MC-Home-assistant is not a valid add-on repository

![image](https://github.com/Kajkac/ZTE-MC-Home-assistant/assets/168814561/0d419a2c-713b-4194-b8b4-5dd7a3045aab)

Thank you in advance

**Comment by brunopiras** [comment]
There's not repository, you must install manually.

I think the developer working on it.

**Comment by YichGa** [comment]
Thank you!
